### ISSUE TITLE
jar Not Found

### ISSUE THREAD

**Issue by ggiri-bib** [in28minutes/docker-crash-course#4]
/bin/sh: [java,-jar,/tmp/hello-world-rest-api.jar]: not found

**Comment by in28minutes** [comment]
Can you run mvn clean install before building docker image?

Is the name of the jar right? Are you using a different name?

hello-world-rest-api.jar

**Comment by VPrachi** [comment]
Yes I have done mvn clean but didn't work.

I Have solved this using the following command:

`CMD exec java -jar "$FINALNAME"
`
Command Like :

`docker container commit --change='CMD exec java -jar "/tmp/hello-world-rest-api.jar"' naughty_knuth in28min/hello-world-rest-api:manual3`

let me know this is correct approach?

**Comment by ggiri-bib** [comment]
Yes I have done mvn clean but didn't work.

I Have solved this using the following command:

`CMD exec java -jar "$FINALNAME"
`
Command Like :

`docker container commit --change='CMD exec java -jar "/tmp/hello-world-rest-api.jar"' naughty_knuth in28min/hello-world-rest-api:manual3`

let me know this is the correct approach?

**Comment by in28minutes** [comment]
Looks great.
